# Generated by Django 5.2.8 on 2025-11-23 19:01

import django.contrib.contenttypes.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codings', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contenttypes.contenttype',),
            managers=[
                ('objects', django.contrib.contenttypes.models.ContentTypeManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'App Type',
                'verbose_name_plural': 'App Types',
                'unique_together': {('id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('order', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('app_label', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.FileField(blank=True, default='app_icons/default_icon.png', null=True, upload_to='app_icons/')),
                ('is_menu', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(blank=True, help_text='The parent app of this app, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_parnet', to='apps.app')),
                ('codingCategory', models.ManyToManyField(blank=True, related_name='app_codingcategory', to='codings.codingcategory')),
                ('appType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.apptype')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'unique_together': {('app_label', 'appType')},
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.FileField(blank=True, default='Versions/initialize.zip', null=True, upload_to='Versions/')),
                ('release_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.app')),
                ('appVersion', models.ForeignKey(blank=True, help_text='The previous version of this app version, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.appversion')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'unique_together': {('version', 'app')},
            },
        ),
    ]
