# Generated by Django 5.2.8 on 2025-12-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_app_create_by_remove_app_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='app',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='app',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='app',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='updated_by',
        ),
    ]
