# Generated by Django 5.2.8 on 2026-01-06 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_app_created_at_app_created_by_app_is_active_and_more'),
        ('codings', '0006_alter_coding_options_alter_codingcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='apptype',
            options={'verbose_name': 'app type', 'verbose_name_plural': 'app types'},
        ),
        migrations.AlterModelOptions(
            name='appversion',
            options={'verbose_name': 'App version', 'verbose_name_plural': 'App versions'},
        ),
        migrations.AlterField(
            model_name='app',
            name='app',
            field=models.ForeignKey(blank=True, help_text='The parent app of this app, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_parnet', to='apps.app', verbose_name='Parent app'),
        ),
        migrations.AlterField(
            model_name='app',
            name='appType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.apptype', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_label',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=' App Label'),
        ),
        migrations.AlterField(
            model_name='app',
            name='codingCategory',
            field=models.ManyToManyField(blank=True, related_name='app_codingcategory', to='codings.codingcategory', verbose_name='Coding categories'),
        ),
        migrations.AlterField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='app',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(blank=True, default='app_icons/default_icon.png', null=True, upload_to='app_icons/', verbose_name='App icon'),
        ),
        migrations.AlterField(
            model_name='app',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='app',
            name='is_menu',
            field=models.BooleanField(default=False, verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name app'),
        ),
        migrations.AlterField(
            model_name='app',
            name='order',
            field=models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='app',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='app',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='App URL'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='app type id'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='name',
            field=models.CharField(max_length=100, verbose_name=' name type'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.app', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='appVersion',
            field=models.ForeignKey(blank=True, help_text='The previous version of this app version, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.appversion', verbose_name='Previous version'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='path',
            field=models.FileField(blank=True, default='Versions/initialize.zip', null=True, upload_to='Versions/', verbose_name='Release file'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='release_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(max_length=100, verbose_name='App version'),
        ),
    ]
