# Generated by Django 6.0.1 on 2026-01-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_app_options_alter_apptype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='app',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='app',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='app',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='app',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='apptype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='updated_by',
        ),
    ]
