# Generated by Django 5.2.9 on 2026-01-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_app_created_at_remove_app_created_by_and_more'),
        ('codings', '0006_alter_coding_options_alter_codingcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='codings',
            field=models.ManyToManyField(blank=True, related_name='app_codings', to='codings.coding', verbose_name='Codings'),
        ),
    ]
