# Generated by Django 5.2.9 on 2026-01-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_app_codings'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_core',
            field=models.BooleanField(default=False, help_text='If true, this app is mandatory in all releases.', verbose_name='Is Core App'),
        ),
    ]
