# Success Codes - GENERAL
ACTION_SUCCESS = "GENERAL.ACTION_SUCCESS"

# User Codes - AUTH
USER_CREATED = "AUTH.USER_CREATED"
USER_UPDATED = "AUTH.USER_UPDATED"
USER_DELETED = "AUTH.USER_DELETED"
USER_FROZEN = "AUTH.USER_FROZEN"
USER_UNFROZEN = "AUTH.USER_UNFROZEN"
PASSWORD_CHANGED = "AUTH.PASSWORD_CHANGED"
PASSWORD_RESET = "AUTH.PASSWORD_RESET"
GROUPS_ASSIGNED = "AUTH.GROUPS_ASSIGNED"
ROLES_ASSIGNED = "AUTH.ROLES_ASSIGNED"
STRUCTURES_ASSIGNED = "AUTH.STRUCTURES_ASSIGNED"
PERMISSIONS_ASSIGNED = "AUTH.PERMISSIONS_ASSIGNED"
CODING_CATEGORIES_ASSIGNED = "AUTH.CODING_CATEGORIES_ASSIGNED"
CODINGS_ASSIGNED = "AUTH.CODINGS_ASSIGNED"

# App Codes - APP_MANAGEMENT
APP_TYPE_CREATED = "APP_MANAGEMENT.APP_TYPE_CREATED"
APP_TYPE_UPDATED = "APP_MANAGEMENT.APP_TYPE_UPDATED"
APP_TYPE_DELETED = "APP_MANAGEMENT.APP_TYPE_DELETED"
APP_TYPE_FROZEN = "APP_MANAGEMENT.APP_TYPE_FROZEN"

APP_CREATED = "APP_MANAGEMENT.APP_CREATED"
APP_UPDATED = "APP_MANAGEMENT.APP_UPDATED"
APP_DELETED = "APP_MANAGEMENT.APP_DELETED"
APP_FROZEN = "APP_MANAGEMENT.APP_FROZEN"

APP_VERSION_CREATED = "APP_MANAGEMENT.APP_VERSION_CREATED"
APP_VERSION_UPDATED = "APP_MANAGEMENT.APP_VERSION_UPDATED"
APP_VERSION_DELETED = "APP_MANAGEMENT.APP_VERSION_DELETED"
APP_VERSION_FROZEN = "APP_MANAGEMENT.APP_VERSION_FROZEN"

# Client Codes - BENEFICIARIES, LEVEL_MANAGEMENT & STRUCTURE_MANAGEMENT
BENEFICIARY_CREATED = "BENEFICIARIES.BENEFICIARY_CREATED"
BENEFICIARY_UPDATED = "BENEFICIARIES.BENEFICIARY_UPDATED"
BENEFICIARY_DELETED = "BENEFICIARIES.BENEFICIARY_DELETED"
BENEFICIARY_FROZEN = "BENEFICIARIES.BENEFICIARY_FROZEN"

# Level Codes - LEVEL_MANAGEMENT (منفصل عن STRUCTURE_MANAGEMENT)
LEVEL_CREATED = "LEVEL_MANAGEMENT.LEVEL_CREATED"
LEVEL_UPDATED = "LEVEL_MANAGEMENT.LEVEL_UPDATED"
LEVEL_DELETED = "LEVEL_MANAGEMENT.LEVEL_DELETED"
LEVEL_FROZEN = "LEVEL_MANAGEMENT.LEVEL_FROZEN"

# Structure Codes - STRUCTURE_MANAGEMENT
STRUCTURE_CREATED = "STRUCTURE_MANAGEMENT.STRUCTURE_CREATED"
STRUCTURE_UPDATED = "STRUCTURE_MANAGEMENT.STRUCTURE_UPDATED"
STRUCTURE_DELETED = "STRUCTURE_MANAGEMENT.STRUCTURE_DELETED"
STRUCTURE_FROZEN = "STRUCTURE_MANAGEMENT.STRUCTURE_FROZEN"

# Coding Codes - CODING
CODING_CATEGORY_CREATED = "CODING.CODING_CATEGORY_CREATED"
CODING_CATEGORY_UPDATED = "CODING.CODING_CATEGORY_UPDATED"
CODING_CATEGORY_DELETED = "CODING.CODING_CATEGORY_DELETED"
CODING_CATEGORY_FROZEN = "CODING.CODING_CATEGORY_FROZEN"

CODING_CREATED = "CODING.CODING_CREATED"
CODING_UPDATED = "CODING.CODING_UPDATED"
CODING_DELETED = "CODING.CODING_DELETED"
CODING_FROZEN = "CODING.CODING_FROZEN"

# Release Codes - RELEASES
RELEASE_CREATED = "RELEASES.RELEASE_CREATED"
RELEASE_UPDATED = "RELEASES.RELEASE_UPDATED"
RELEASE_DELETED = "RELEASES.RELEASE_DELETED"
RELEASE_FROZEN = "RELEASES.RELEASE_FROZEN"

# Group/Role Codes - RBAC
GROUP_CREATED = "RBAC.GROUP_CREATED"
GROUP_UPDATED = "RBAC.GROUP_UPDATED"
GROUP_DELETED = "RBAC.GROUP_DELETED"
GROUP_FROZEN = "RBAC.GROUP_FROZEN"

ROLE_CREATED = "RBAC.ROLE_CREATED"
ROLE_UPDATED = "RBAC.ROLE_UPDATED"
ROLE_DELETED = "RBAC.ROLE_DELETED"
ROLE_FROZEN = "RBAC.ROLE_FROZEN"

PERMISSION_CREATED = "RBAC.PERMISSION_CREATED"
PERMISSION_UPDATED = "RBAC.PERMISSION_UPDATED"
PERMISSION_DELETED = "RBAC.PERMISSION_DELETED"
PERMISSION_FROZEN = "RBAC.PERMISSION_FROZEN"

# Error Codes - GENERAL
INVALID_OLD_PASSWORD = "GENERAL.INVALID_OLD_PASSWORD"
VALIDATION_ERROR = "GENERAL.VALIDATION_ERROR"
PERMISSION_DENIED = "GENERAL.PERMISSION_DENIED"
NOT_FOUND = "GENERAL.NOT_FOUND"
SERVER_ERROR = "GENERAL.SERVER_ERROR"
PROTECTED_ERROR = "GENERAL.PROTECTED_ERROR"


# CRM Codes
CUSTOMER_CREATED = "CRM.CUSTOMER_CREATED"
CUSTOMER_UPDATED = "CRM.CUSTOMER_UPDATED"
CUSTOMER_DELETED = "CRM.CUSTOMER_DELETED"
CUSTOMER_FROZEN = "CRM.CUSTOMER_FROZEN"

LEAD_CREATED = "CRM.LEAD_CREATED"
LEAD_UPDATED = "CRM.LEAD_UPDATED"
LEAD_DELETED = "CRM.LEAD_DELETED"
LEAD_FROZEN = "CRM.LEAD_FROZEN"

OPPORTUNITY_CREATED = "CRM.OPPORTUNITY_CREATED"
OPPORTUNITY_UPDATED = "CRM.OPPORTUNITY_UPDATED"
OPPORTUNITY_DELETED = "CRM.OPPORTUNITY_DELETED"
OPPORTUNITY_FROZEN = "CRM.OPPORTUNITY_FROZEN"

NOTE_CREATED = "CRM.NOTE_CREATED"
NOTE_UPDATED = "CRM.NOTE_UPDATED"
NOTE_DELETED = "CRM.NOTE_DELETED"
NOTE_FROZEN = "CRM.NOTE_FROZEN"

CONTACT_CREATED = "CRM.CONTACT_CREATED"
CONTACT_UPDATED = "CRM.CONTACT_UPDATED"
CONTACT_DELETED = "CRM.CONTACT_DELETED"
CONTACT_FROZEN = "CRM.CONTACT_FROZEN"