# Generated by Django 5.2.7 on 2025-11-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_name', models.CharField(max_length=200, verbose_name='الاسم العام')),
                ('specific_name', models.CharField(max_length=200, unique=True, verbose_name='الاسم الخاص')),
                ('type', models.CharField(choices=[('normal', 'عادي'), ('tree', 'شجرة')], default='normal', max_length=10, verbose_name='النوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('CodingCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='codings.codingcategory', verbose_name='معتمد على فئة')),
            ],
            options={
                'verbose_name': 'فئة رموز',
                'verbose_name_plural': 'فئات الرموز',
            },
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('category', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True)),
                ('coding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coding_parnet', to='codings.coding', verbose_name='الرمز الأب')),
                ('codingCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codings.codingcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'رمز',
                'verbose_name_plural': 'الرموز',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
