# Generated by Django 5.2.8 on 2025-12-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codings', '0003_remove_coding_create_by_remove_coding_update_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
