# Generated by Django 5.2.8 on 2025-12-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codings', '0004_codingcategory_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coding',
            name='coding',
        ),
        migrations.RemoveField(
            model_name='coding',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coding',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='coding',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='coding',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='codingcategory',
            name='CodingCategory',
        ),
        migrations.RemoveField(
            model_name='codingcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='codingcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='codingcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='codingcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='codingcategory',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='coding',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='codings.coding', verbose_name='الرمز الأب'),
        ),
        migrations.AddField(
            model_name='codingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='codings.codingcategory', verbose_name='معتمد على فئة'),
        ),
    ]
