# Generated by Django 5.2.8 on 2026-01-06 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codings', '0005_remove_coding_coding_remove_coding_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coding',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Code', 'verbose_name_plural': 'Codes'},
        ),
        migrations.AlterModelOptions(
            name='codingcategory',
            options={'verbose_name': 'Coding category', 'verbose_name_plural': 'Coding categories'},
        ),
        migrations.AlterField(
            model_name='coding',
            name='codingCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codings.codingcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='coding',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coding',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='coding',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='codings.coding', verbose_name='Parent code'),
        ),
        migrations.AlterField(
            model_name='codingcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='codingcategory',
            name='general_name',
            field=models.CharField(max_length=200, verbose_name='General name'),
        ),
        migrations.AlterField(
            model_name='codingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='codings.codingcategory', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='codingcategory',
            name='specific_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Specific name'),
        ),
        migrations.AlterField(
            model_name='codingcategory',
            name='type',
            field=models.CharField(choices=[('normal', 'عادي'), ('tree', 'شجرة')], default='normal', max_length=10, verbose_name='Type'),
        ),
    ]
