# Generated by Django 5.2.9 on 2026-01-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codings', '0006_alter_coding_options_alter_codingcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Symbol/Code'),
        ),
    ]
