# Generated by Django 5.2.7 on 2025-11-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('public_name', models.CharField(max_length=100)),
                ('pravite_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, default='images/default_image.png', null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('right_address', models.TextField(blank=True, null=True)),
                ('left_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiary',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(blank=True, default=0, help_text='The number of structures at this level.', null=True)),
                ('level', models.ForeignKey(blank=True, help_text='The parent level of this level, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sublvls', to='clients.level')),
            ],
            options={
                'verbose_name': 'Structure level',
                'verbose_name_plural': 'Structure levels',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, default='images/default_image.png', null=True, upload_to='images/')),
                ('is_branch', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('right_address', models.TextField(blank=True, null=True)),
                ('left_address', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ManyToManyField(blank=True, related_name='beneficiary_structure', to='clients.beneficiary')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.level')),
                ('structure', models.ForeignKey(blank=True, help_text='The parent structure of this structure, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stractures_parnet', to='clients.structure')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
            },
        ),
    ]
