# Generated by Django 5.2.7 on 2025-11-28 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='structure',
            field=models.ForeignKey(blank=True, help_text='The parent structure of this structure, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='clients.structure'),
        ),
    ]
