# Generated by Django 5.2.8 on 2025-12-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_beneficiary_create_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
