# Generated by Django 5.2.8 on 2026-01-06 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_beneficiary_is_active_level_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='image',
            field=models.FileField(blank=True, default='images/default_image.png', null=True, upload_to='images/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='left_address',
            field=models.TextField(blank=True, null=True, verbose_name='Left header'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='order',
            field=models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='pravite_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Private name'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='public_name',
            field=models.CharField(max_length=100, verbose_name='Public name'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='right_address',
            field=models.TextField(blank=True, null=True, verbose_name='Right header'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='level',
            name='count',
            field=models.IntegerField(blank=True, default=0, help_text='The number of structures at this level.', null=True, verbose_name='Number of levels'),
        ),
        migrations.AlterField(
            model_name='level',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='level',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.ForeignKey(blank=True, help_text='The parent level of this level, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sublvls', to='clients.level', verbose_name='Parent level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='level',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='level',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='image',
            field=models.FileField(blank=True, default='images/default_image.png', null=True, upload_to='images/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='is_branch',
            field=models.BooleanField(default=False, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='left_address',
            field=models.TextField(blank=True, null=True, verbose_name='Left header'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.level', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Structure name'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='order',
            field=models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='right_address',
            field=models.TextField(blank=True, null=True, verbose_name='Right header'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='structure',
            field=models.ForeignKey(blank=True, help_text='The parent structure of this structure, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='clients.structure', verbose_name='Parent structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
