# Generated by Django 6.0.1 on 2026-01-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_beneficiary_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='structure',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_structure', to='clients.beneficiary'),
        ),
    ]
