# Generated by Django 5.2.8 on 2025-12-07 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Action Time')),
                ('action_flag', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed')], max_length=32, verbose_name='Action Flag')),
                ('app_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='App Label')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model Name')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ('-action_time',),
            },
        ),
    ]
