# Generated by Django 5.2.8 on 2025-12-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_alter_activitylog_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_flag',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('force_logout', 'Force Logout')], max_length=32, verbose_name='Action Flag'),
        ),
    ]
