# Generated by Django 5.2.8 on 2026-01-06 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0004_alter_activitylog_action_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ('-action_time',), 'verbose_name': 'Activity log', 'verbose_name_plural': 'Activity logs'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_flag',
            field=models.CharField(choices=[('create', 'انشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('login', 'تسجيل الدخول'), ('logout', 'تسجيل الخروج'), ('login_failed', 'فشل تسجيل الدخول'), ('force_logout', 'تسجيل الخروج القسري')], max_length=32, verbose_name='Action type'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Action time'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='app_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='App name'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen name'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object representation'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User agent'),
        ),
    ]
