# Generated by Django 5.2.7 on 2025-11-04 15:06

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0001_initial'),
        ('codings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_visibility', models.CharField(choices=[('self', 'بيانات المستخدم فقط'), ('department', 'بيانات الهيكل الإداري'), ('all', 'جميع البيانات في النظام')], default='self', max_length=10, verbose_name='صلاحيات رؤية البيانات')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='يجب تغيير كلمة المرور')),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='users.user', verbose_name='المسؤول المباشر')),
                ('stractures', models.ManyToManyField(blank=True, help_text='The stractures of this user belongs to.', related_name='stractures_user', to='clients.structure')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('coding', models.ManyToManyField(to='codings.coding')),
                ('codingCategory', models.ManyToManyField(to='codings.codingcategory')),
                ('group', models.ForeignKey(blank=True, help_text='The group roles of this group, if any.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='group_roles', to='users.group')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
