# Generated by Django 5.2.7 on 2025-11-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='coding',
            field=models.ManyToManyField(blank=True, to='codings.coding'),
        ),
        migrations.AlterField(
            model_name='role',
            name='codingCategory',
            field=models.ManyToManyField(blank=True, to='codings.codingcategory'),
        ),
    ]
