# Generated by Django 5.2.8 on 2025-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_coding_alter_role_codingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default='77777', verbose_name='رقم الهاتف'),
        ),
    ]
