# Generated by Django 5.2.8 on 2026-01-06 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_beneficiary_options_and_more'),
        ('codings', '0006_alter_coding_options_alter_codingcategory_options_and_more'),
        ('users', '0006_user_token_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='role',
            name='coding',
            field=models.ManyToManyField(blank=True, to='codings.coding', verbose_name='Codings'),
        ),
        migrations.AlterField(
            model_name='role',
            name='codingCategory',
            field=models.ManyToManyField(blank=True, to='codings.codingcategory', verbose_name='Coding categories'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_visibility',
            field=models.CharField(choices=[('self', 'بيانات المستخدم فقط'), ('department', 'بيانات الهيكل الإداري'), ('all', 'جميع البيانات في النظام')], default='self', max_length=10, verbose_name='Data visibility'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direct_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='users.user', verbose_name='Direct manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Must change password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stractures',
            field=models.ManyToManyField(blank=True, help_text='The stractures of this user belongs to.', related_name='stractures_user', to='clients.structure', verbose_name='Structures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Token version'),
        ),
    ]
