# Generated by Django 6.0.1 on 2026-01-20 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0009_app_is_core'),
        ('clients', '0007_remove_structure_beneficiary_structure_beneficiary'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0008_alter_user_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=200, verbose_name='Release name')),
                ('descraption', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_update', models.BooleanField(default=False, verbose_name='Update')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Release date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='release_exports/', verbose_name='Exported File')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Version')),
                ('base_release', models.ForeignKey(blank=True, help_text='The release this was cloned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.release', verbose_name='Base Release')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Releases',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='ClientRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('active_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active From')),
                ('active_to', models.DateTimeField(blank=True, null=True, verbose_name='Active To')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_releases', to='clients.beneficiary', verbose_name='Beneficiary')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='releases.release', verbose_name='Release')),
            ],
            options={
                'verbose_name': 'Client Release',
                'verbose_name_plural': 'Client Releases',
            },
        ),
        migrations.CreateModel(
            name='ReleaseApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Year')),
                ('is_core', models.BooleanField(default=False, help_text='Inherited from App.', verbose_name='Is Core')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.app', verbose_name='Application')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release', verbose_name='Release')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.appversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Release Application',
                'verbose_name_plural': 'Release Applications',
                'unique_together': {('release', 'app')},
            },
        ),
        migrations.AddField(
            model_name='release',
            name='apps',
            field=models.ManyToManyField(blank=True, related_name='apps_release', through='releases.ReleaseApp', to='apps.app'),
        ),
        migrations.CreateModel(
            name='ReleaseBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.beneficiary', verbose_name='Beneficiary')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release', verbose_name='Release')),
            ],
            options={
                'verbose_name': 'Release Beneficiary',
                'verbose_name_plural': 'Release Beneficiaries',
                'unique_together': {('release', 'beneficiary')},
            },
        ),
        migrations.CreateModel(
            name='ReleaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group', verbose_name='Group')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release', verbose_name='Release')),
            ],
            options={
                'verbose_name': 'Release Group',
                'verbose_name_plural': 'Release Groups',
                'unique_together': {('release', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ReleaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('can_create', models.BooleanField(default=True, verbose_name='Can Create')),
                ('can_read', models.BooleanField(default=True, verbose_name='Can Read')),
                ('can_update', models.BooleanField(default=True, verbose_name='Can Update')),
                ('can_delete', models.BooleanField(default=True, verbose_name='Can Delete')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.app', verbose_name='Application')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_models', to='releases.release', verbose_name='Release')),
            ],
            options={
                'verbose_name': 'Release Model',
                'verbose_name_plural': 'Release Models',
                'unique_together': {('release', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='ReleaseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('service_code', models.CharField(max_length=100, verbose_name='Service Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.app', verbose_name='Application')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_services', to='releases.release', verbose_name='Release')),
            ],
            options={
                'verbose_name': 'Release Service',
                'verbose_name_plural': 'Release Services',
                'unique_together': {('release', 'service_code')},
            },
        ),
        migrations.CreateModel(
            name='ReleaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release', verbose_name='Release')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Release User',
                'verbose_name_plural': 'Release Users',
                'unique_together': {('release', 'user')},
            },
        ),
    ]
