# Generated by Django 5.2.8 on 2025-11-23 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descraption', models.TextField(blank=True, null=True)),
                ('is_update', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('apps', models.ManyToManyField(blank=True, related_name='apps_release', to='apps.app')),
                ('beneficiary', models.ManyToManyField(blank=True, related_name='beneficiary_release', to='clients.beneficiary')),
            ],
            options={
                'verbose_name': 'الاصدارات',
                'verbose_name_plural': 'الاصدارات',
            },
        ),
    ]
