# Generated by Django 5.2.8 on 2025-11-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups_release', to='users.group'),
        ),
    ]
