# Generated by Django 6.0.1 on 2026-01-21 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_app_is_core'),
        ('clients', '0007_remove_structure_beneficiary_structure_beneficiary'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('releases', '0001_initial'),
        ('users', '0008_alter_user_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=200, verbose_name='Update Name')),
                ('version', models.CharField(max_length=50, verbose_name='Update Version')),
                ('update_type', models.CharField(choices=[('bugfix', 'Bug Fix'), ('improvement', 'Improvement'), ('feature', 'New Feature'), ('security', 'Security Patch'), ('hotfix', 'Hotfix')], default='improvement', max_length=20, verbose_name='Update Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('testing', 'Testing'), ('ready', 'Ready for Deployment'), ('deployed', 'Deployed'), ('deprecated', 'Deprecated')], default='draft', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('changelog', models.TextField(blank=True, help_text='Markdown formatted changelog.', null=True, verbose_name='Changelog')),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='update_exports/', verbose_name='Exported File')),
                ('requires_migration', models.BooleanField(default=False, help_text='Whether this update includes database migrations.', verbose_name='Requires Migration')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If true, clients must apply this update.', verbose_name='Mandatory Update')),
                ('min_compatible_version', models.CharField(blank=True, help_text='Minimum client version required for this update.', max_length=50, null=True, verbose_name='Minimum Compatible Version')),
                ('base_release', models.ForeignKey(help_text='The release this update is based on.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='releases.release', verbose_name='Base Release')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_updates', to='users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('rollback_available', models.BooleanField(default=True, verbose_name='Rollback Available')),
                ('rollback_file', models.FileField(blank=True, help_text='Backup for rollback purposes.', null=True, upload_to='update_rollbacks/', verbose_name='Rollback File')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_updates', to='users.user', verbose_name='Applied By')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_updates', to='clients.beneficiary', verbose_name='Beneficiary')),
                ('client_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_updates', to='releases.clientrelease', verbose_name='Client Release')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_updates', to='releases.update', verbose_name='Update')),
            ],
            options={
                'verbose_name': 'Client Update',
                'verbose_name_plural': 'Client Updates',
                'ordering': ['-scheduled_at', '-id'],
                'unique_together': {('update', 'client_release')},
            },
        ),
        migrations.CreateModel(
            name='UpdateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('app', 'Application'), ('model', 'Model'), ('service', 'Service'), ('view', 'View/API'), ('template', 'Template/UI'), ('setting', 'Configuration'), ('migration', 'Database Migration'), ('static', 'Static File'), ('translation', 'Translation')], max_length=20, verbose_name='Item Type')),
                ('file_path', models.CharField(blank=True, help_text='Relative path to the affected file.', max_length=500, null=True, verbose_name='File Path')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('fixed', 'Fixed')], max_length=20, verbose_name='Change Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of application for this change.', verbose_name='Order')),
                ('app', models.ForeignKey(blank=True, help_text='The application this change belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.app', verbose_name='Application')),
                ('content_type', models.ForeignKey(blank=True, help_text='For model-type changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Model')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='releases.update', verbose_name='Update')),
            ],
            options={
                'verbose_name': 'Update Item',
                'verbose_name_plural': 'Update Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('exported', 'Exported'), ('applied', 'Applied'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Action')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Performed At')),
                ('details', models.JSONField(blank=True, help_text='Additional details in JSON format.', null=True, verbose_name='Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('client_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='releases.clientupdate', verbose_name='Client Update')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Performed By')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='releases.update', verbose_name='Update')),
            ],
            options={
                'verbose_name': 'Update Log',
                'verbose_name_plural': 'Update Logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
